### ISSUE TITLE
Undisclosed maximum length for data values

### ISSUE THREAD

**Issue by jmz-b** [UoW-CPC/Asclepios-Server#11]
I ran into the following error after trying to add some new data after upgrading to the `0.2_postgres` tag.

```
sse-db_1      | 2020-08-12 12:18:46.757 UTC [255] ERROR:  value too long for type character varying(300)
sse-db_1      | 2020-08-12 12:18:46.757 UTC [255] STATEMENT:  INSERT INTO "api_ciphertext" ("jsonId", "data") VALUES ('16', '{''iv'': ''YWJjZGVmZw=='', ''v'': 1, ''iter'': 10000, ''ks'': 128, ''ts'': 64, ''mode'': ''ccm'', ''adata'': '''', ''cipher'': ''aes'', ''salt'': ''YWJjMTIzIT8='', ''ct'': ''20RKcEzEW3L5gADrcDidlpBlAiqc6f5bkt8Eqo39Mo7OMQ/8+F15U1lKu1blDLsXV0PDGgToNq2cH+HTKzE2vXIqX9a8JFQXlSykqP92c8vindqz2r73n136Eua2cmM4acYmDdmUfQQHGw5tDxm5S2jhrg==''}') RETURNING "api_ciphertext"."id"
sse_1         | 2020-08-12 12:18:46,757 DEBUG [django.db.backends:130] utils 59 140463892092736 (0.001) INSERT INTO "api_ciphertext" ("jsonId", "data") VALUES ('16', '{''iv'': ''YWJjZGVmZw=='', ''v'': 1, ''iter'': 10000, ''ks'': 128, ''ts'': 64, ''mode'': ''ccm'', ''adata'': '''', ''cipher'': ''aes'', ''salt'': ''YWJjMTIzIT8='', ''ct'': ''20RKcEzEW3L5gADrcDidlpBlAiqc6f5bkt8Eqo39Mo7OMQ/8+F15U1lKu1blDLsXV0PDGgToNq2cH+HTKzE2vXIqX9a8JFQXlSykqP92c8vindqz2r73n136Eua2cmM4acYmDdmUfQQHGw5tDxm5S2jhrg==''}') RETURNING "api_ciphertext"."id"; args=('16', "{'iv': 'YWJjZGVmZw==', 'v': 1, 'iter': 10000, 'ks': 128, 'ts': 64, 'mode': 'ccm', 'adata': '', 'cipher': 'aes', 'salt': 'YWJjMTIzIT8=', 'ct': '20RKcEzEW3L5gADrcDidlpBlAiqc6f5bkt8Eqo39Mo7OMQ/8+F15U1lKu1blDLsXV0PDGgToNq2cH+HTKzE2vXIqX9a8JFQXlSykqP92c8vindqz2r73n136Eua2cmM4acYmDdmUfQQHGw5tDxm5S2jhrg=='}")
sse_1         | 2020-08-12 12:18:46,757 DEBUG [django.db.backends:130] utils 60 140463892092736 (0.001) INSERT INTO "api_map" ("address", "value") VALUES ('2cc41b1c042e3216d0d8ed55cdcc56acab167eb598687a79aa13aed1652800d3', '16') RETURNING "api_map"."id"; args=('2cc41b1c042e3216d0d8ed55cdcc56acab167eb598687a79aa13aed1652800d3', '16')
sse_1         | 2020-08-12 12:18:46,758 ERROR [django.request.tastypie:321] resources 59 140463892092736 Internal Server Error: /api/v1/ciphertext/
sse_1         | Traceback (most recent call last):
sse_1         |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 86, in _execute
sse_1         |     return self.cursor.execute(sql, params)
sse_1         | psycopg2.errors.StringDataRightTruncation: value too long for type character varying(300)
sse_1         | 
sse_1         | 
sse_1         | The above exception was the direct cause of the following exception:
sse_1         | 
sse_1         | Traceback (most recent call last):
sse_1         |   File "/usr/local/lib/python3.7/site-packages/tastypie/resources.py", line 227, in wrapper
sse_1         |     response = callback(request, *args, **kwargs)
sse_1         |   File "/usr/local/lib/python3.7/site-packages/tastypie/resources.py", line 467, in dispatch_list
sse_1         |     return self.dispatch('list', request, **kwargs)
sse_1         |   File "/usr/local/lib/python3.7/site-packages/tastypie/resources.py", line 499, in dispatch
sse_1         |     response = method(request, **kwargs)
sse_1         |   File "/usr/local/lib/python3.7/contextlib.py", line 74, in inner
sse_1         |     return func(*args, **kwds)
sse_1         |   File "/usr/local/lib/python3.7/site-packages/tastypie/resources.py", line 2367, in patch_list
sse_1         |     return super(BaseModelResource, self).patch_list(request, **kwargs)
sse_1         |   File "/usr/local/lib/python3.7/site-packages/tastypie/resources.py", line 1644, in patch_list
sse_1         |     self.obj_create(bundle=bundle)
sse_1         |   File "/usr/local/lib/python3.7/site-packages/tastypie/resources.py", line 2251, in obj_create
sse_1         |     return self.save(bundle)
sse_1         |   File "/usr/local/lib/python3.7/site-packages/tastypie/resources.py", line 2405, in save
sse_1         |     bundle.obj.save()
sse_1         |   File "/usr/local/lib/python3.7/site-packages/django/db/models/base.py", line 746, in save
sse_1         |     force_update=force_update, update_fields=update_fields)
sse_1         |   File "/usr/local/lib/python3.7/site-packages/django/db/models/base.py", line 784, in save_base
sse_1         |     force_update, using, update_fields,
sse_1         |   File "/usr/local/lib/python3.7/site-packages/django/db/models/base.py", line 887, in _save_table
sse_1         |     results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
sse_1         |   File "/usr/local/lib/python3.7/site-packages/django/db/models/base.py", line 926, in _do_insert
sse_1         |     using=using, raw=raw,
sse_1         |   File "/usr/local/lib/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
sse_1         |     return getattr(self.get_queryset(), name)(*args, **kwargs)
sse_1         |   File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 1204, in _insert
sse_1         |     return query.get_compiler(using=using).execute_sql(returning_fields)
sse_1         |   File "/usr/local/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1392, in execute_sql
sse_1         |     cursor.execute(sql, params)
sse_1         |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 100, in execute
sse_1         |     return super().execute(sql, params)
sse_1         |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 68, in execute
sse_1         |     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
sse_1         |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
sse_1         |     return executor(sql, params, many, context)
sse_1         |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 86, in _execute
sse_1         |     return self.cursor.execute(sql, params)
sse_1         |   File "/usr/local/lib/python3.7/site-packages/django/db/utils.py", line 90, in __exit__
sse_1         |     raise dj_exc_value.with_traceback(traceback) from exc_value
sse_1         |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 86, in _execute
sse_1         |     return self.cursor.execute(sql, params)
sse_1         | django.db.utils.DataError: value too long for type character varying(300)
sse_1         | 
sse_1         | 2020-08-12 12:18:46,759 ERROR [django.request:228] log 59 140463892092736 Internal Server Error: /api/v1/ciphertext/

```

I did some investigation and it appears there is an upper limit on the length of data values, for example.

```js
// THIS WORKS
uploadData({'a': 'a'.repeat(104)}, '15', '123', '123')

// THIS THROWS THE ABOVE ERROR
uploadData({'a': 'a'.repeat(105)}, '15', '123', '123')
```

This is being caused by the length of the JSON object being stored in the `data` field on the `ciphertext` table.

```py
>>> len('''{''iv'': ''YWJjZGVmZw=='', ''v'': 1, ''iter'': 10000, ''ks'': 128, ''ts'': 64, ''mode'': ''ccm'', ''adata'': '''', ''cipher'': ''aes'', ''salt'': ''YWJjMTIzIT8='', ''ct'': ''20RKcEzEW3L5gADrcDidlpBlAiqc6f5bkt8Eqo39Mo7OMQ/8+F15U1lKu1blDLsXV0PDGgToNq2cH+HTKzE2vXIqX9a8JFQXlSykqP92c8vindqz2r73n136Eua2cmM4acYmDdmUfQQHGw5tDxm5S2jhrg==''}''')
305
```

I would suggest changing [this](https://github.com/UoW-CPC/Asclepios-Server/blob/master/api/models.py#L7) line to use a django [TextField](https://docs.djangoproject.com/en/3.0/ref/models/fields/#textfield) and creating a migration. This will use a `text` field instead of a `varchar` in the sql storage. `text` fields do not have a maximum length.

**Comment by hvandang** [comment]
@jmz-b : Thanks, James. I've updated it to Develop branch, but not merge to Master branch yet. It will be merged in the next release.
